import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'zh-TW';

type Translations = {
  [key in Language]: {
    [key: string]: string;
  };
};

const translations: Translations = {
  'en': {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.bookkeeping': 'Bookkeeping',
    'nav.invoices': 'Invoices & Quotes',
    'nav.projects': 'Projects',
    'nav.priceCheck': 'Price Check AI',
    'nav.settings': 'Settings',
    'nav.clients': 'Client List',
    'nav.calendar': 'Calendar',
    'nav.footer': '© 2025 SmartQxAI',
    'nav.reports': 'Financial Reports',

    // Dashboard
    'dash.welcome': 'Good Evening,',
    'dash.user': 'User',
    'dash.quote': 'Your time is limited, don\'t waste it.',
    'dash.weather': 'Local Weather',
    'dash.weather.desc': 'Cloudy',
    'dash.event': 'Christmas',
    'dash.days': 'Days',
    'dash.netAsset': 'Net Assets',
    'dash.activeQuotes': 'Active Quotes',
    'dash.invalid': 'Invalid Quote',
    'dash.invalidQuote': 'Invalid Quote',
    'dash.viewInvalid': 'Invalid Quotes',
    'dash.closedCases': 'Closed Cases',
    'dash.totalInvoices': 'Invoices',
    'dash.invoicesIssued': 'Invoices Issued',
    'dash.viewInvoices': 'Invoices Issued List',
    'dash.quickActions': 'Quick Actions',
    'dash.recentQuotes': 'Recent Quotes',
    'dash.clients': 'Clients',
    'dash.newQuote': 'New Quote',
    'dash.projectStatus': 'Project Status',
    'dash.ledger': 'AI Bookkeeping',
    'dash.calendar': 'Calendar',
    'dash.reports': 'Financial Statements',
    'dash.createFirst': 'No quotes yet. Create your first one!',
    'dash.compare': 'vs Last Month',
    'dash.netBalance': 'Net Balance',
    'dash.totalIncome': 'Total Income',
    'dash.totalExpense': 'Total Expenses',
    'dash.pendingInvoices': 'Pending Invoices',
    'dash.unpaidAmount': 'Unpaid amount',
    'dash.cashFlow': 'Cash Flow Overview',
    'dash.noData': 'No transaction data available yet.',
    'dash.chart.income': 'Income',
    'dash.chart.expense': 'Expense',
    'dash.subtitle': 'Welcome back to your financial command center.',
    'dash.itemPriceLookup': 'Item Price Lookup',
    'dash.noInvalid': 'No invalid/expired quotes found.',
    'dash.noInvoices': 'No invoices issued yet.',
    'dash.validity': 'Validity',
    'dash.daysLeft': 'days left',
    'dash.expired': 'Expired',

    // Bookkeeping
    'book.title': 'Transactions',
    'book.subtitle': 'Track your daily income and expenses.',
    'book.addNew': 'Add New',
    'book.all': 'All',
    'book.income': 'Income',
    'book.expense': 'Expense',
    'book.personalExpense': 'Personal Expense',
    'book.date': 'Date',
    'book.type': 'Type',
    'book.desc': 'Description',
    'book.merchant': 'Merchant / Store',
    'book.item': 'Purchased Item',
    'book.location': 'Location',
    'book.category': 'Category',
    'book.amount': 'Amount',
    'book.scanReceipt': 'Scan Receipt with AI',
    'book.cameraScan': 'Camera Scan',
    'book.uploadAlbum': 'Upload / Album',
    'book.analyzing': 'Analyzing Receipt...',
    'book.uploadTip': 'Click or drop receipt image here',
    'book.noTrans': 'No transactions found. Add one to get started.',
    'book.modal.title': 'Add Transaction',
    'book.placeholder.desc': 'e.g. Monthly Rent',
    'book.placeholder.merchant': 'e.g. Apple Store',
    'book.placeholder.item': 'e.g. iPhone 15 Pro',
    'book.placeholder.location': 'e.g. Taipei',
    'book.cancel': 'Cancel',
    'book.save': 'Save',
    'book.details': 'Transaction Details',
    'book.selectProject': 'Link to Project (Optional)',
    'book.projectExpense': 'Project Expense',
    'book.selectProjectPlaceholder': 'Select a Project...',
    
    // Categories
    'cat.Salary': 'Salary',
    'cat.Freelance': 'Freelance',
    'cat.Investment': 'Investment',
    'cat.Sales': 'Sales',
    'cat.Other': 'Other',
    'cat.Food': 'Food',
    'cat.Transport': 'Transport',
    'cat.Rent': 'Rent',
    'cat.Utilities': 'Utilities',
    'cat.Entertainment': 'Entertainment',
    'cat.Shopping': 'Shopping',
    'cat.Health': 'Health',

    // Invoices
    'inv.title': 'Invoices & Quotes',
    'inv.subtitle': 'Manage and track your professional documents.',
    'inv.createNew': 'Create New',
    'inv.noDocs': 'No documents found. Create your first invoice or quotation.',
    'inv.draft': 'Draft',
    'inv.sent': 'Sent',
    'inv.paid': 'Paid',
    'inv.back': 'Back to List',
    'inv.newDoc': 'New Document',
    'inv.editDoc': 'Edit Document',
    'inv.type': 'Document Type',
    'inv.quotation': 'Quotation',
    'inv.invoice': 'Invoice',
    'inv.clientName': 'Client Name',
    'inv.clientPlace': 'Client Company or Name',
    'inv.number': 'Number',
    'inv.date': 'Date',
    'inv.dueDate': 'Due Date',
    'inv.items': 'Items',
    'inv.addItem': 'Add Item',
    'inv.desc': 'Description',
    'inv.itemNote': 'Item Note (Optional)',
    'inv.qty': 'Qty',
    'inv.price': 'Price',
    'inv.totalAmount': 'Total Amount',
    'inv.print': 'Print / PDF',
    'inv.billTo': 'Bill To',
    'inv.subtotal': 'Subtotal',
    'inv.total': 'Total',
    'inv.notes': 'Notes',
    'inv.paymentTerms': 'Payment Terms',
    'inv.deposit': 'Deposit',
    'inv.balance': 'Balance Due',
    'inv.selectClient': 'Select Client',
    'inv.selectClientTitle': 'Select Client',
    'inv.noClientsAlert': 'No clients found. Please add a client first in the Client Management section.',
    'inv.searchClient': 'Search clients...',
    'inv.close': 'Close',
    'inv.project': 'Project',
    'inv.selectProject': 'Select Project (Optional)',
    'inv.convertToInvoice': 'Convert to Invoice',
    'inv.archiveClient': 'Complete & Archive Client',
    'inv.workflow': 'Workflow',
    'inv.backToProjects': 'Back to Projects',
    'inv.viewProject': 'View Project',
    'inv.added': 'Document Saved',
    'inv.generateTerms': 'AI Terms Generation',
    'inv.quoteMode': 'Quote Mode',
    'inv.modeCompany': 'Company',
    'inv.modeIndividual': 'Individual',
    'inv.docLanguage': 'Doc Language',
    'inv.currency': 'Currency',
    'inv.taxRate': 'Tax Rate (%)',
    'inv.discount': 'Discount',
    'inv.depositPercent': 'Deposit (%)',
    'inv.progressPercent': 'Progress Payment (%)',
    'inv.progressPayment': 'Progress Payment',
    'inv.includesTax': 'Includes Tax',
    'inv.tax': 'Tax',
    'inv.authorizedSignature': 'Authorized Signature',
    'inv.notesPlaceholder': 'Add payment terms or additional notes...',
    'inv.emailComposer': 'AI Email Composer',
    'inv.emailDrafting': 'Drafting for',
    'inv.emailTone': 'Email Tone',
    'inv.toneProfessional': 'Professional',
    'inv.toneFriendly': 'Friendly',
    'inv.toneUrgent': 'Urgent',
    'inv.generateAI': 'Generate with AI',
    'inv.subject': 'Subject',
    'inv.subjectPlaceholder': 'AI will generate subject...',
    'inv.body': 'Body',
    'inv.bodyPlaceholder': 'Select a tone and click Generate...',
    'inv.attachmentReminder': 'Attachment Reminder',
    'inv.attachmentDesc': 'Use the preview button to download/print the PDF first. Then, in the Gmail window, drag and drop the file to attach it.',
    'inv.openGmail': 'Open in Gmail',
    'inv.createOneNow': 'Create one now',
    'inv.noDocsProject': 'No invoices or quotes found for this project.',

    // Projects
    'proj.title': 'Projects',
    'proj.subtitle': 'Manage projects and link them to clients.',
    'proj.addNew': 'New Project',
    'proj.name': 'Project Name',
    'proj.status': 'Status',
    'proj.active': 'Active',
    'proj.completed': 'Completed',
    'proj.noData': 'No projects found. Start a new project to track work.',
    'proj.selectClient': 'Select Client',
    'proj.edit': 'Edit Project',
    'proj.search': 'Search projects...',
    'proj.created': 'Created:',
    'proj.noDesc': 'No description provided.',
    'proj.selectClientPlaceholder': 'Select a Client...',
    'proj.details': 'Project details...',
    
    // Project Statuses
    'proj.st.NOT_SET': 'Not Set',
    'proj.st.QUOTE_SENT': 'Quote Sent',
    'proj.st.DEPOSIT_RECEIVED': 'Deposit Received',
    'proj.st.PROGRESS_PAYMENT': 'Progress Payment Received',
    'proj.st.COMPLETED': 'Completed & Settled',
    'proj.st.ARCHIVED': 'Project Archived',

    // Price Check
    'price.title': 'Market Price Checker',
    'price.subtitle': 'Instant price intelligence powered by AI & Google Search.',
    'price.placeholder': 'E.g., iPhone 15, Drywall (auto-translates)...',
    'price.button': 'Check Price',
    'price.analyzing': 'Analyzing...',
    'price.result': 'Analysis Result',
    'price.sources': 'Sources & References',
    'price.helper': 'Enter item to search (auto-translates), choose country, check price',
    'price.identify': 'Identifying Item...',
    'price.photoSearch': 'Photo Search',
    'price.buyNow': 'Buy Now',
    'price.optionsFound': 'options found',
    'price.checking': 'Checking sources...',

    // Clients
    'client.title': 'Client Management',
    'client.subtitle': 'Manage your customer database.',
    'client.addNew': 'Add Client',
    'client.name': 'Client Name',
    'client.edit': 'Edit Client',
    'client.email': 'Email',
    'client.phone': 'Phone',
    'client.address': 'Address',
    'client.taxId': 'Tax ID',
    'client.notes': 'Notes',
    'client.noData': 'No clients found. Add your first client.',
    'client.search': 'Search clients...',
    'client.active': 'Active',
    'client.archived': 'Archived',
    'client.archive': 'Archive',
    'client.restore': 'Restore',
    'client.status': 'Status',
    'client.projects': 'Projects',
    'client.manageProjects': 'Manage Projects',
    'client.createQuote': 'Create Quote',
    'client.for': 'For Client:',
    'client.unknown': 'Unknown Client',

    // Calendar
    'cal.title': 'Calendar',
    'cal.subtitle': 'Schedule events and set reminders.',
    'cal.addEvent': 'Add Event',
    'cal.editEvent': 'Edit Event',
    'cal.eventTitle': 'Event Title',
    'cal.time': 'Time',
    'cal.description': 'Description',
    'cal.reminder': 'Reminder',
    'cal.none': 'None',
    'cal.atTime': 'At time of event',
    'cal.5min': '5 minutes before',
    'cal.15min': '15 minutes before',
    'cal.30min': '30 minutes before',
    'cal.1hour': '1 hour before',
    'cal.1day': '1 day before',
    'cal.custom': 'Custom',
    'cal.minutes': 'min before',
    'cal.today': 'Today',
    'cal.mon': 'Mon',
    'cal.tue': 'Tue',
    'cal.wed': 'Wed',
    'cal.thu': 'Thu',
    'cal.fri': 'Fri',
    'cal.sat': 'Sat',
    'cal.sun': 'Sun',
    'cal.noEvents': 'No events this month',

    // Settings
    'set.title': 'User Settings',
    'set.subtitle': 'Manage your profile, language, and invoice defaults.',
    'set.basicInfo': 'Basic Information',
    'set.financial': 'Financial Settings',
    'set.companyName': 'Company / Individual Name',
    'set.contactName': 'Contact Name',
    'set.address': 'Address',
    'set.email': 'Email',
    'set.phone': 'Phone',
    'set.taxId': 'Tax ID / VAT Number',
    'set.deposit': 'Deposit Percentage (%)',
    'set.secondPayment': 'Second Payment (Progress) (%)',
    'set.acceptance': 'Acceptance Payment (%)',
    'set.saveSuccess': 'Settings Saved Successfully!',
    'set.language': 'Language Settings',
    'set.lang.en': 'English (US)',
    'set.lang.zh': 'Traditional Chinese',
    'set.branding': 'Branding & Signature',
    'set.companyLogo': 'Company Logo',
    'set.uploadLogo': 'Upload Logo',
    'set.logoFormat': 'PNG, JPG (Max 2MB)',
    'set.signature': 'Signature',
    'set.uploadSignature': 'Upload Signature',
    'set.sigFormat': 'Transparent PNG Recommended',
    'set.total': 'Total',
    'set.warning': 'Warning: Total does not equal 100%',

    // Reports
    'rep.title': 'Financial Reports',
    'rep.subtitle': 'Generate tax-ready Excel reports for U.S. accounting standards.',
    'rep.period': 'Reporting Period',
    'rep.year': 'Year',
    'rep.month': 'Month',
    'rep.annual': 'Annual Report',
    'rep.generate': 'Generate Report',
    'rep.download': 'Download Excel',
    'rep.preview': 'Report Preview',
    'rep.noData': 'No data available for the selected period.',
    'rep.project': 'Project Name',
    'rep.client': 'Client',
    'rep.revenue': 'Revenue',
    'rep.expenses': 'Expenses',
    'rep.net': 'Net Income',
    'rep.status': 'Status',
    'rep.total': 'Grand Total',
    'rep.allMonths': 'All Months',

    // Common
    'common.taxId': 'Tax ID',
  },
  'zh-TW': {
    // Navigation
    'nav.dashboard': '儀表板',
    'nav.bookkeeping': '記帳',
    'nav.invoices': '發票與報價單',
    'nav.projects': '專案管理',
    'nav.priceCheck': 'AI 價格查詢',
    'nav.settings': '設定',
    'nav.clients': '客戶列表',
    'nav.calendar': '行事曆',
    'nav.footer': '© 2025 SmartQxAI',
    'nav.reports': '財務報表',

    // Dashboard
    'dash.welcome': '晚安，',
    'dash.user': '使用者',
    'dash.quote': '時間有限，請勿浪費。',
    'dash.weather': '當地天氣',
    'dash.weather.desc': '多雲',
    'dash.event': '聖誕節',
    'dash.days': '天',
    'dash.netAsset': '淨資產',
    'dash.activeQuotes': '進行中報價',
    'dash.invalid': '無效報價',
    'dash.invalidQuote': '無效報價',
    'dash.viewInvalid': '查看無效報價',
    'dash.closedCases': '已結案',
    'dash.totalInvoices': '發票總數',
    'dash.invoicesIssued': '已開發票',
    'dash.viewInvoices': '查看已開發票',
    'dash.quickActions': '快速動作',
    'dash.recentQuotes': '最近報價',
    'dash.clients': '客戶',
    'dash.newQuote': '新報價單',
    'dash.projectStatus': '專案狀態',
    'dash.ledger': 'AI 記帳',
    'dash.calendar': '行事曆',
    'dash.reports': '財務報表',
    'dash.createFirst': '尚無報價單。建立您的第一張報價單！',
    'dash.compare': '與上月相比',
    'dash.netBalance': '淨收支',
    'dash.totalIncome': '總收入',
    'dash.totalExpense': '總支出',
    'dash.pendingInvoices': '待處理發票',
    'dash.unpaidAmount': '未付金額',
    'dash.cashFlow': '現金流概覽',
    'dash.noData': '目前沒有交易資料。',
    'dash.chart.income': '收入',
    'dash.chart.expense': '支出',
    'dash.subtitle': '歡迎回到您的財務控制中心。',
    'dash.itemPriceLookup': '商品查價',
    'dash.noInvalid': '沒有無效或過期的報價單。',
    'dash.noInvoices': '尚未開立發票。',
    'dash.validity': '有效期',
    'dash.daysLeft': '天剩餘',
    'dash.expired': '已過期',

    // Bookkeeping
    'book.title': '交易紀錄',
    'book.subtitle': '追蹤您的每日收入與支出。',
    'book.addNew': '新增交易',
    'book.all': '全部',
    'book.income': '收入',
    'book.expense': '支出',
    'book.personalExpense': '個人支出',
    'book.date': '日期',
    'book.type': '類型',
    'book.desc': '描述',
    'book.merchant': '商家 / 店名',
    'book.item': '購買項目',
    'book.location': '地點',
    'book.category': '類別',
    'book.amount': '金額',
    'book.scanReceipt': 'AI 掃描收據',
    'book.cameraScan': '相機掃描',
    'book.uploadAlbum': '上傳 / 相簿',
    'book.analyzing': '分析收據中...',
    'book.uploadTip': '點擊或拖放收據圖片至此',
    'book.noTrans': '未找到交易紀錄。新增一筆以開始。',
    'book.modal.title': '新增交易',
    'book.placeholder.desc': '例如：每月房租',
    'book.placeholder.merchant': '例如：Apple Store',
    'book.placeholder.item': '例如：iPhone 15 Pro',
    'book.placeholder.location': '例如：台北',
    'book.cancel': 'Cancel',
    'book.save': '儲存',
    'book.details': '交易詳情',
    'book.selectProject': '連結至專案 (選填)',
    'book.projectExpense': '專案支出',
    'book.selectProjectPlaceholder': '選擇一個專案...',
    
    // Categories
    'cat.Salary': '薪資',
    'cat.Freelance': '接案',
    'cat.Investment': '投資',
    'cat.Sales': '銷售',
    'cat.Other': '其他',
    'cat.Food': '飲食',
    'cat.Transport': '交通',
    'cat.Rent': '房租',
    'cat.Utilities': '水電費',
    'cat.Entertainment': '娛樂',
    'cat.Shopping': '購物',
    'cat.Health': '醫療',

    // Invoices
    'inv.title': '發票與報價單',
    'inv.subtitle': '管理與追蹤您的商業文件。',
    'inv.createNew': '建立新文件',
    'inv.noDocs': '未找到文件。建立您的第一張發票或報價單。',
    'inv.draft': '草稿',
    'inv.sent': '已發送',
    'inv.paid': '已付款',
    'inv.back': '返回列表',
    'inv.newDoc': '新文件',
    'inv.editDoc': '編輯文件',
    'inv.type': '文件類型',
    'inv.quotation': '報價單',
    'inv.invoice': '發票',
    'inv.clientName': '客戶名稱',
    'inv.clientPlace': '客戶公司或姓名',
    'inv.number': '編號',
    'inv.date': '日期',
    'inv.dueDate': '到期日',
    'inv.items': '項目',
    'inv.addItem': '新增項目',
    'inv.desc': '描述',
    'inv.itemNote': '項目備註 (選填)',
    'inv.qty': '數量',
    'inv.price': '單價',
    'inv.totalAmount': '總金額',
    'inv.print': '列印 / PDF',
    'inv.billTo': '受款人',
    'inv.subtotal': '小計',
    'inv.total': '總計',
    'inv.notes': '備註',
    'inv.paymentTerms': '付款條件',
    'inv.deposit': '訂金',
    'inv.balance': '應付餘額',
    'inv.selectClient': '選擇客戶',
    'inv.selectClientTitle': '選擇客戶',
    'inv.noClientsAlert': '未找到客戶。請先在客戶管理部分新增客戶。',
    'inv.searchClient': '搜尋客戶...',
    'inv.close': '關閉',
    'inv.project': '專案',
    'inv.selectProject': '選擇專案 (選填)',
    'inv.convertToInvoice': '轉為發票',
    'inv.archiveClient': '完成並歸檔客戶',
    'inv.workflow': '工作流程',
    'inv.backToProjects': '返回專案列表',
    'inv.viewProject': '查看專案',
    'inv.added': '文件已儲存',
    'inv.generateTerms': 'AI 生成條款',
    'inv.quoteMode': '報價模式',
    'inv.modeCompany': '公司',
    'inv.modeIndividual': '個人',
    'inv.docLanguage': '文件語言',
    'inv.currency': '貨幣',
    'inv.taxRate': '稅率 (%)',
    'inv.discount': '折扣',
    'inv.depositPercent': '訂金 (%)',
    'inv.progressPercent': '進度款 (%)',
    'inv.progressPayment': '進度款',
    'inv.includesTax': '含稅',
    'inv.tax': '稅金',
    'inv.authorizedSignature': '授權簽名',
    'inv.notesPlaceholder': '新增付款條件或其他備註...',
    'inv.emailComposer': 'AI 郵件撰寫',
    'inv.emailDrafting': '正在撰寫',
    'inv.emailTone': '郵件語氣',
    'inv.toneProfessional': '專業',
    'inv.toneFriendly': '友善',
    'inv.toneUrgent': '緊急',
    'inv.generateAI': '使用 AI 生成',
    'inv.subject': '主旨',
    'inv.subjectPlaceholder': 'AI 將生成主旨...',
    'inv.body': '內文',
    'inv.bodyPlaceholder': '選擇語氣並點擊生成...',
    'inv.attachmentReminder': '附件提醒',
    'inv.attachmentDesc': '請先使用預覽按鈕下載/列印 PDF。然後在 Gmail 視窗中將檔案拖放以附加。',
    'inv.openGmail': '在 Gmail 中開啟',
    'inv.createOneNow': '立即建立',
    'inv.noDocsProject': '此專案尚無發票或報價單。',

    // Projects
    'proj.title': '專案管理',
    'proj.subtitle': '管理專案並連結至客戶。',
    'proj.addNew': '新專案',
    'proj.name': '專案名稱',
    'proj.status': '狀態',
    'proj.active': '進行中',
    'proj.completed': '已完成',
    'proj.noData': '未找到專案。開始一個新專案以追蹤工作。',
    'proj.selectClient': '選擇客戶',
    'proj.edit': '編輯專案',
    'proj.search': '搜尋專案...',
    'proj.created': '建立於：',
    'proj.noDesc': '未提供描述。',
    'proj.selectClientPlaceholder': '選擇客戶...',
    'proj.details': '專案詳情...',
    
    // Project Statuses
    'proj.st.NOT_SET': '未設定',
    'proj.st.QUOTE_SENT': '報價已送出',
    'proj.st.DEPOSIT_RECEIVED': '已收訂金',
    'proj.st.PROGRESS_PAYMENT': '已收進度款',
    'proj.st.COMPLETED': '已完成並結案',
    'proj.st.ARCHIVED': '專案已歸檔',

    // Price Check
    'price.title': '市場價格查詢',
    'price.subtitle': '由 AI 與 Google 搜尋提供的即時價格情報。',
    'price.placeholder': '例如：iPhone 15, 建築石膏板 (自動翻譯)...',
    'price.button': '查詢價格',
    'price.analyzing': '分析中...',
    'price.result': '分析結果',
    'price.sources': '來源與參考',
    'price.helper': '輸入商品搜尋(自動翻譯)，選擇國家，查詢價格',
    'price.identify': '辨識物品中...',
    'price.photoSearch': '拍照搜尋',
    'price.buyNow': '立即購買',
    'price.optionsFound': '個搜尋結果',
    'price.checking': '正在搜尋來源...',

    // Clients
    'client.title': '客戶管理',
    'client.subtitle': '管理您的客戶資料庫。',
    'client.addNew': '新增客戶',
    'client.name': '客戶名稱',
    'client.edit': '編輯客戶',
    'client.email': '電子郵件',
    'client.phone': '電話',
    'client.address': '地址',
    'client.taxId': '統編/稅號',
    'client.notes': '備註',
    'client.noData': '未找到客戶。新增您的第一個客戶。',
    'client.search': '搜尋客戶...',
    'client.active': '進行中',
    'client.archived': '已歸檔',
    'client.archive': '歸檔',
    'client.restore': '還原',
    'client.status': '狀態',
    'client.projects': '專案列表',
    'client.manageProjects': '管理專案',
    'client.createQuote': '建立報價單',
    'client.for': '客戶：',
    'client.unknown': '未知客戶',

    // Calendar
    'cal.title': '行事曆',
    'cal.subtitle': '安排行程並設定提醒。',
    'cal.addEvent': '新增事件',
    'cal.editEvent': '編輯事件',
    'cal.eventTitle': '事件標題',
    'cal.time': '時間',
    'cal.description': '描述',
    'cal.reminder': '提醒',
    'cal.none': '無',
    'cal.atTime': '事件發生時',
    'cal.5min': '5 分鐘前',
    'cal.15min': '15 分鐘前',
    'cal.30min': '30 分鐘前',
    'cal.1hour': '1 小時前',
    'cal.1day': '1 day before',
    'cal.custom': '自訂',
    'cal.minutes': '分鐘前',
    'cal.today': '今天',
    'cal.mon': '一',
    'cal.tue': '二',
    'cal.wed': '三',
    'cal.thu': '四',
    'cal.fri': '五',
    'cal.sat': '六',
    'cal.sun': '日',
    'cal.noEvents': '本月無事件',

    // Settings
    'set.title': '用戶設定',
    'set.subtitle': '管理您的基本資料、語言與發票預設值。',
    'set.basicInfo': '基本資料',
    'set.financial': '財務設定',
    'set.companyName': '公司 / 個人名稱',
    'set.contactName': '聯絡人',
    'set.address': '地址',
    'set.email': '電子郵件',
    'set.phone': '電話',
    'set.taxId': '統一編號 / 稅籍編號',
    'set.deposit': '訂金百分比 (%)',
    'set.secondPayment': '二次付款(進度款)百分比 (%)',
    'set.acceptance': '驗收尾款百分比 (%)',
    'set.saveSuccess': '設定已成功儲存！',
    'set.language': '語言設定',
    'set.lang.en': '英文 (English)',
    'set.lang.zh': '繁體中文',
    'set.branding': '品牌與簽名',
    'set.companyLogo': '公司 Logo',
    'set.uploadLogo': '上傳 Logo',
    'set.logoFormat': 'PNG, JPG (最大 2MB)',
    'set.signature': '簽名檔',
    'set.uploadSignature': '上傳簽名',
    'set.sigFormat': '建議使用透明背景 PNG',
    'set.total': '總計',
    'set.warning': '警告：總計不等於 100%',

    // Reports
    'rep.title': '財務報表',
    'rep.subtitle': '產生符合美國會計標準的稅務 Excel 報表。',
    'rep.period': '報表期間',
    'rep.year': '年份',
    'rep.month': '月份',
    'rep.annual': '年度報表',
    'rep.generate': '產生報表',
    'rep.download': '下載 Excel',
    'rep.preview': '報表預覽',
    'rep.noData': '所選期間無資料。',
    'rep.project': '專案名稱',
    'rep.client': '客戶',
    'rep.revenue': '收入',
    'rep.expenses': '支出',
    'rep.net': '淨利',
    'rep.status': '狀態',
    'rep.total': '總計',
    'rep.allMonths': '所有月份',

    // Common
    'common.taxId': '統編',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    // 1. Check Local Storage
    const saved = localStorage.getItem('app_language');
    if (saved === 'en' || saved === 'zh-TW') return saved;

    // 2. Check Browser Preference
    const browserLang = navigator.language;
    if (browserLang.toLowerCase().startsWith('zh')) {
      return 'zh-TW';
    }
    return 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};